// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juqzyziobgwrzphnemox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1cXp5emlvYmd3cnpwaG5lbW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMzAzMjMsImV4cCI6MjA1OTcwNjMyM30.QQlFTvr-AiXa7KWAzFpqbiM6uaWOL1bfFrHpgmp-ARo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);